//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS.ScaleModelsShop.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IS.ScaleModelsShop.Application.Resources.ValidationErrors", typeof(ValidationErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category with the same &apos;{PropertyName}&apos; already exists..
        /// </summary>
        internal static string Category_Common_SameCategoryAlreadyExist {
            get {
                return ResourceManager.GetString("Category_Common_SameCategoryAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; is not in the correct format. Expected format - &quot;http(s)://&quot; or &quot;www.&quot; following with the site name and domain name (e.g., www.example.org).
        /// </summary>
        internal static string Manufacturer_Common_ProvidedStringIsNotValidUrl {
            get {
                return ResourceManager.GetString("Manufacturer_Common_ProvidedStringIsNotValidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided &apos;{PropertyName}&apos; has unacceptable domain name( e.g., &quot;.ru&quot; or &quot;.su&quot;).
        /// </summary>
        internal static string Manufacturer_Common_ProvidedUrlHasUnappropriateDomainName {
            get {
                return ResourceManager.GetString("Manufacturer_Common_ProvidedUrlHasUnappropriateDomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer with the same &apos;{PropertyName}&apos; already exists..
        /// </summary>
        internal static string Manufacturer_Common_SameManufacturerAlreadyExist {
            get {
                return ResourceManager.GetString("Manufacturer_Common_SameManufacturerAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category with ID &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string Product_Categoty_CategotyDoesNotExist {
            get {
                return ResourceManager.GetString("Product_Categoty_CategotyDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid for &apos;{PropertyName}&apos; can not be Empty GUID. Please provide correct GUID..
        /// </summary>
        internal static string Product_Common_GuidCanNotBeEmptyGuid {
            get {
                return ResourceManager.GetString("Product_Common_GuidCanNotBeEmptyGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price of the product cannot be equal to &apos;{0}&apos;.Should be greater that zero..
        /// </summary>
        internal static string Product_Common_PriceShouldBeGreaterThanZero {
            get {
                return ResourceManager.GetString("Product_Common_PriceShouldBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product with the same &apos;{PropertyName}&apos; already exists..
        /// </summary>
        internal static string Product_Common_SameProductAlreadyExist {
            get {
                return ResourceManager.GetString("Product_Common_SameProductAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer with ID &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string Product_Manufacturer_ManufacturerDoesNotExist {
            get {
                return ResourceManager.GetString("Product_Manufacturer_ManufacturerDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product {0} not found..
        /// </summary>
        internal static string Products_Common_ProductDoesNotExist {
            get {
                return ResourceManager.GetString("Products_Common_ProductDoesNotExist", resourceCulture);
            }
        }
    }
}
